# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toy.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ttoy.proto\" \n\x06Member\x12\n\n\x02id\x18\x01 \x01(\t\x12\n\n\x02pw\x18\x02 \x01(\t\"*\n\x05Reply\x12\x0b\n\x03key\x18\x01 \x01(\x08\x12\x14\n\x03log\x18\x02 \x01(\x0b\x32\x07.Member\"\x15\n\x06MulNum\x12\x0b\n\x03num\x18\x01 \x01(\x05\"\'\n\x06Result\x12\x0b\n\x03\x65xp\x18\x01 \x01(\t\x12\x10\n\x08solution\x18\x02 \x01(\x05\x32\x44\n\x03Toy\x12\x1a\n\x05Login\x12\x07.Member\x1a\x06.Reply\"\x00\x12!\n\tCalcualte\x12\x07.MulNum\x1a\x07.Result\"\x00\x30\x01\x62\x06proto3')



_MEMBER = DESCRIPTOR.message_types_by_name['Member']
_REPLY = DESCRIPTOR.message_types_by_name['Reply']
_MULNUM = DESCRIPTOR.message_types_by_name['MulNum']
_RESULT = DESCRIPTOR.message_types_by_name['Result']
Member = _reflection.GeneratedProtocolMessageType('Member', (_message.Message,), {
  'DESCRIPTOR' : _MEMBER,
  '__module__' : 'toy_pb2'
  # @@protoc_insertion_point(class_scope:Member)
  })
_sym_db.RegisterMessage(Member)

Reply = _reflection.GeneratedProtocolMessageType('Reply', (_message.Message,), {
  'DESCRIPTOR' : _REPLY,
  '__module__' : 'toy_pb2'
  # @@protoc_insertion_point(class_scope:Reply)
  })
_sym_db.RegisterMessage(Reply)

MulNum = _reflection.GeneratedProtocolMessageType('MulNum', (_message.Message,), {
  'DESCRIPTOR' : _MULNUM,
  '__module__' : 'toy_pb2'
  # @@protoc_insertion_point(class_scope:MulNum)
  })
_sym_db.RegisterMessage(MulNum)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), {
  'DESCRIPTOR' : _RESULT,
  '__module__' : 'toy_pb2'
  # @@protoc_insertion_point(class_scope:Result)
  })
_sym_db.RegisterMessage(Result)

_TOY = DESCRIPTOR.services_by_name['Toy']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MEMBER._serialized_start=13
  _MEMBER._serialized_end=45
  _REPLY._serialized_start=47
  _REPLY._serialized_end=89
  _MULNUM._serialized_start=91
  _MULNUM._serialized_end=112
  _RESULT._serialized_start=114
  _RESULT._serialized_end=153
  _TOY._serialized_start=155
  _TOY._serialized_end=223
# @@protoc_insertion_point(module_scope)
